Train: 
 device: cuda:0
 batch_size: 4
 n_epochs: 200
 dataset_name: horse2zebra
 checkpoint_interval: 10
 n_blocks: 9
 lr: 0.0002
 sample_interval: 100
 lambda_cyc: 10.0
 lambda_identity: 5.0

Image:
 channels: 3
 img_width: 256
 img_height: 256

